### ISSUE TITLE
Selecting any room from a map causes an error

### ISSUE THREAD

**Issue by tortyse** [SCCapstone/RoomScheduling#47]

**Comment by tzoonami** [comment]
Cannot reproduce

**Comment by tortyse** [comment]
The targets for the rooms were wrong

**Comment by tortyse** [comment]
For some reason i still get this error when testing on the local machine. deploying the code shows working rooms

**Comment by tzoonami** [comment]
You don't have the list of rooms in your local datastore, you have to add them manually

**Comment by tzoonami** [comment]
http://pastebin.com/i2dD5TyE
